# Generated by Django 2.1.3 on 2018-11-13 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_globalcatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Название организации', max_length=100)),
                ('contacts', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='E-mail', max_length=254)),
                ('max_expense', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Возможное превышение расходов')),
                ('description', models.TextField(verbose_name='Описание')),
                ('sum_at_date', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Остаток на')),
                ('date', models.DateField(blank=True, null=True, verbose_name='дату')),
                ('adv_fac', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Дополнительные услуги на сумму')),
                ('pays', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Платежи за месяц')),
                ('epay', models.CharField(max_length=10, verbose_name='E-Pay аккаунт')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contracttype', models.CharField(help_text='Тип договора', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaysType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystype', models.CharField(help_text='Тип платежей', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='contracttype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ContractType'),
        ),
        migrations.AddField(
            model_name='contract',
            name='paystype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.PaysType'),
        ),
    ]
