# Generated by Django 2.1.3 on 2018-11-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181113_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
