# Generated by Django 2.1.3 on 2018-11-13 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181113_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttarif',
            name='start',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Начало действия тарифа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contracttarif',
            name='stop',
            field=models.DateField(default='3000-01-01', verbose_name='Конец действия тарифа'),
        ),
    ]
