# Generated by Django 2.1.3 on 2018-11-13 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181113_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculate_point', models.CharField(default='127.0.0.1', max_length=20, verbose_name='Точка обсчета')),
                ('from_net', models.CharField(default='0.0.0.0/0', max_length=20, verbose_name='Из сети')),
                ('to_net', models.CharField(help_text='IP-адрес/маска', max_length=20, verbose_name='На сеть')),
                ('from_int', models.CharField(default='0', max_length=20, verbose_name='С интерфейса')),
                ('to_int', models.CharField(default='0', max_length=20, verbose_name='На интерфейс')),
                ('description', models.CharField(max_length=20, verbose_name='Описание')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('tarif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Facilitie', verbose_name='Тариф')),
            ],
        ),
    ]
