# Generated by Django 2.1.3 on 2018-11-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
                ('description', models.CharField(max_length=40, verbose_name='Описание')),
                ('typeserv', models.CharField(choices=[('p', 'ежемесячный платеж'), ('s', 'разовая услуга')], max_length=40, verbose_name='Тип')),
                ('cost', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='')),
                ('comment', models.TextField(verbose_name='')),
            ],
        ),
    ]
