# Generated by Django 2.1.3 on 2018-11-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitie',
            name='vector',
            field=models.CharField(choices=[('in', 'входящий'), ('out', 'исходящий'), ('max', 'превалирующий'), ('min', 'наименьший'), ('bw', 'условный безлимит')], help_text='(in,out,max) - расчет по входящему, исходящему, превалирующему трафику, bw для условных безлимитов', max_length=10, verbose_name='Направление'),
        ),
    ]
