# Generated by Django 2.1.3 on 2018-11-14 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20181113_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='tarif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ContractTarif', verbose_name='Тариф'),
        ),
    ]
