# Generated by Django 2.1.3 on 2018-11-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_client_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': (('can_disable_cli', 'Set disable clients'),)},
        ),
    ]
