# Generated by Django 2.1.3 on 2018-11-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20181115_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': (('can_disable_cli', 'Set disable clients'), ('can_full_view', 'Show owners'))},
        ),
    ]
